jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.17]
        steps:
            - uses: FranzDiebold/github-env-vars-action@v2
            - uses: actions/checkout@v1
            - name: Check cache
              id: cache
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}-0
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Use Node ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: 'https://npm.pkg.github.com'
            - name: install dependencies
              run: yarn install
            - name: run linting
            - name: run tests
              run: yarn test
            - name: run coneverage
              run: yarn test:coverage
            - name: run badges
              run: yarn test:badges  
            - name: build code
              run: yarn build
            - name: copy file branch